# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband', models.CharField(max_length=10)),
                ('wife', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
