# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:06
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.RemoveField(
            model_name='main',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='main',
            name='image',
        ),
        migrations.RemoveField(
            model_name='main',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='main',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image10',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image11',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image12',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image13',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image14',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image7',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image8',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
        migrations.AddField(
            model_name='main',
            name='image9',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=mainpage.models.get_image_path),
        ),
    ]
