# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import maincomment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image4', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image5', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image6', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image7', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image8', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image9', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image10', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image11', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image12', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image13', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
                ('image14', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=maincomment.models.get_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincomment.MainComment'),
        ),
    ]
